///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CoinModel {
/*
{
  "id": "bitcoin",
  "symbol": "btc",
  "name": "Bitcoin",
  "image": "https://assets.coingecko.com/coins/images/1/large/bitcoin.png?1547033579",
  "current_price": 22627,
  "market_cap": 432934333778,
  "market_cap_rank": 1,
  "fully_diluted_valuation": 475955473029,
  "total_volume": 42965060936,
  "high_24h": 22768,
  "low_24h": 22048,
  "price_change_24h": -36.429102022808365,
  "price_change_percentage_24h": -0.16074,
  "market_cap_change_24h": 288030060,
  "market_cap_change_percentage_24h": 0.06657,
  "circulating_supply": 19101831,
  "total_supply": 21000000,
  "max_supply": 21000000,
  "ath": 69045,
  "ath_change_percentage": -67.17488,
  "ath_date": "2021-11-10T14:24:11.849Z",
  "atl": 67.81,
  "atl_change_percentage": 33323.33672,
  "atl_date": "2013-07-06T00:00:00.000Z",
  "roi": null,
  "last_updated": "2022-07-24T10:07:48.335Z"
} 
*/

  String? id;
  String? symbol;
  String? name;
  String? image;
  double? currentPrice;
  int? marketCap;
  int? marketCapRank;
  int? fullyDilutedValuation;
  int? totalVolume;
  int? high_24h;
  int? low_24h;
  double? priceChange_24h;
  double? priceChangePercentage_24h;
  int? marketCapChange_24h;
  double? marketCapChangePercentage_24h;
  int? circulatingSupply;
  int? totalSupply;
  int? maxSupply;
  int? ath;
  double? athChangePercentage;
  String? athDate;
  double? atl;
  double? atlChangePercentage;
  String? atlDate;
  String? roi;
  String? lastUpdated;

  CoinModel({
    this.id,
    this.symbol,
    this.name,
    this.image,
    this.currentPrice,
    this.marketCap,
    this.marketCapRank,
    this.fullyDilutedValuation,
    this.totalVolume,
    this.high_24h,
    this.low_24h,
    this.priceChange_24h,
    this.priceChangePercentage_24h,
    this.marketCapChange_24h,
    this.marketCapChangePercentage_24h,
    this.circulatingSupply,
    this.totalSupply,
    this.maxSupply,
    this.ath,
    this.athChangePercentage,
    this.athDate,
    this.atl,
    this.atlChangePercentage,
    this.atlDate,
    this.roi,
    this.lastUpdated,
  });
  CoinModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    symbol = json['symbol']?.toString();
    name = json['name']?.toString();
    image = json['image']?.toString();
    currentPrice = json['current_price']?.toDouble();
    marketCap = json['market_cap']?.toInt();
    marketCapRank = json['market_cap_rank']?.toInt();
    fullyDilutedValuation = json['fully_diluted_valuation']?.toInt();
    totalVolume = json['total_volume']?.toInt();
    high_24h = json['high_24h']?.toInt();
    low_24h = json['low_24h']?.toInt();
    priceChange_24h = json['price_change_24h']?.toDouble();
    priceChangePercentage_24h = json['price_change_percentage_24h']?.toDouble();
    marketCapChange_24h = json['market_cap_change_24h']?.toInt();
    marketCapChangePercentage_24h =
        json['market_cap_change_percentage_24h']?.toDouble();
    circulatingSupply = json['circulating_supply']?.toInt();
    totalSupply = json['total_supply']?.toInt();
    maxSupply = json['max_supply']?.toInt();
    ath = json['ath']?.toInt();
    athChangePercentage = json['ath_change_percentage']?.toDouble();
    athDate = json['ath_date']?.toString();
    atl = json['atl']?.toDouble();
    atlChangePercentage = json['atl_change_percentage']?.toDouble();
    atlDate = json['atl_date']?.toString();
    roi = json['roi']?.toString();
    lastUpdated = json['last_updated']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['symbol'] = symbol;
    data['name'] = name;
    data['image'] = image;
    data['current_price'] = currentPrice;
    data['market_cap'] = marketCap;
    data['market_cap_rank'] = marketCapRank;
    data['fully_diluted_valuation'] = fullyDilutedValuation;
    data['total_volume'] = totalVolume;
    data['high_24h'] = high_24h;
    data['low_24h'] = low_24h;
    data['price_change_24h'] = priceChange_24h;
    data['price_change_percentage_24h'] = priceChangePercentage_24h;
    data['market_cap_change_24h'] = marketCapChange_24h;
    data['market_cap_change_percentage_24h'] = marketCapChangePercentage_24h;
    data['circulating_supply'] = circulatingSupply;
    data['total_supply'] = totalSupply;
    data['max_supply'] = maxSupply;
    data['ath'] = ath;
    data['ath_change_percentage'] = athChangePercentage;
    data['ath_date'] = athDate;
    data['atl'] = atl;
    data['atl_change_percentage'] = atlChangePercentage;
    data['atl_date'] = atlDate;
    data['roi'] = roi;
    data['last_updated'] = lastUpdated;
    return data;
  }
}
